const OWNER='goranrakocevicns-cyber',REPO='deal-ns',BRANCH='main';let token=sessionStorage.getItem('dealns_gh_token')||'';
const $=s=>document.querySelector(s);function api(path,opt={}){return fetch('https://api.github.com/repos/'+OWNER+'/'+REPO+path,{...opt,headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',Authorization:'Bearer '+token,...(opt.headers||{})}}).then(async r=>{const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||'GitHub greška');return j})}
async function getData(){const f=await api('/contents/data.json?ref='+BRANCH);return{data:JSON.parse(decodeURIComponent(escape(atob(f.content.replace(/\n/g,''))))),sha:f.sha}}
function b64utf8(s){return btoa(unescape(encodeURIComponent(s)))}
async function saveData(data,sha,msg){return api('/contents/data.json',{method:'PUT',body:JSON.stringify({message:msg,content:b64utf8(JSON.stringify(data,null,2)+'\n'),sha,branch:BRANCH})})}
function file64(file){return new Promise((res,rej)=>{const r=new FileReader;r.onload=()=>res(String(r.result).split(',')[1]);r.onerror=rej;r.readAsDataURL(file)})}
function cleanName(s){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9._-]+/g,'-').replace(/^-+|-+$/g,'')}
async function upload(file,path){const content=await file64(file);await api('/contents/'+path,{method:'PUT',body:JSON.stringify({message:'Upload '+file.name,content,branch:BRANCH})});return path}
async function login(){token=$('#gh-token').value.trim();$('#login-msg').textContent='Proveravam…';try{await api('');sessionStorage.setItem('dealns_gh_token',token);$('#login-box').hidden=true;$('#editor').hidden=false;await refresh();}catch(e){$('#login-msg').textContent='Prijava nije uspela: '+e.message}}
async function refresh(){const {data}=await getData(),el=$('#admin-list');el.innerHTML=(data.references||[]).length?(data.references||[]).slice().reverse().map(r=>`<div class="admin-item"><strong>${r.title}</strong><a href="reference.html?id=${encodeURIComponent(r.id)}" target="_blank">Otvori</a><button data-del="${r.id}">Obriši</button></div>`).join(''):'Još nema referenci.';el.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>removeRef(b.dataset.del))}
async function removeRef(id){if(!confirm('Obrisati ovu referencu sa sajta?'))return;const {data,sha}=await getData();data.references=(data.references||[]).filter(r=>r.id!==id);await saveData(data,sha,'Delete reference '+id);await refresh()}
$('#login-btn').onclick=login;if(token){$('#gh-token').value=token;login()}
$('#ref-form').onsubmit=async e=>{e.preventDefault();const msg=$('#publish-msg');msg.textContent='Objavljujem…';try{const title=$('#ref-title').value.trim(),id=Date.now()+'-'+cleanName(title),files=[...$('#ref-images').files],urls=[];for(const f of files){const path='assets/references/'+id+'/'+Date.now()+'-'+cleanName(f.name);await upload(f,path);urls.push(path)}const {data,sha}=await getData();data.references=data.references||[];data.references.push({id,title,short:$('#ref-short').value.trim(),description:$('#ref-description').value.trim(),cover:urls[0]||'',images:urls,published:true,created:new Date().toISOString()});await saveData(data,sha,'Publish reference '+title);e.target.reset();msg.textContent='Referenca je objavljena.';await refresh()}catch(err){msg.textContent='Greška: '+err.message}}
$('#gallery-upload').onclick=async()=>{const msg=$('#gallery-msg'),files=[...$('#gallery-images').files];if(!files.length)return;msg.textContent='Dodajem…';try{const urls=[];for(const f of files){const path='assets/gallery/'+Date.now()+'-'+cleanName(f.name);await upload(f,path);urls.push({src:path,title:''})}const {data,sha}=await getData();data.gallery=[...(data.gallery||[]),...urls];await saveData(data,sha,'Add gallery photos');$('#gallery-images').value='';msg.textContent='Fotografije su dodate u galeriju.'}catch(err){msg.textContent='Greška: '+err.message}}
