const SUPABASE_URL='https://qfkfglciujegnyflebjh.supabase.co';
const SUPABASE_KEY='sb_publishable_2ujRYSmQf43wt10vQikHKQ_9wQj79sN';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY),$=s=>document.querySelector(s);
function cleanName(s){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9._-]+/g,'-').replace(/^-+|-+$/g,'')||'file'}
async function isAdmin(uid){const {data,error}=await db.from('admins').select('user_id').eq('user_id',uid).maybeSingle();if(error)throw error;return !!data}
async function showSession(){const {data:{session}}=await db.auth.getSession();if(!session){$('#login-box').hidden=false;$('#editor').hidden=true;return}if(!await isAdmin(session.user.id)){await db.auth.signOut();$('#login-msg').textContent='Ovaj nalog nema administratorsko pravo.';return}$('#login-box').hidden=true;$('#editor').hidden=false;$('#admin-user').textContent=session.user.email;await refresh()}
$('#login-btn').onclick=async()=>{const m=$('#login-msg');m.textContent='Prijavljujem…';const {data,error}=await db.auth.signInWithPassword({email:$('#admin-email').value.trim(),password:$('#admin-password').value});if(error){m.textContent='Prijava nije uspela: '+error.message;return}if(!await isAdmin(data.user.id)){await db.auth.signOut();m.textContent='Ovaj nalog nema administratorsko pravo.';return}m.textContent='';await showSession()};
$('#logout-btn').onclick=async()=>{await db.auth.signOut();location.reload()};
async function upload(file,folder){if(file.size>5*1024*1024)throw new Error(file.name+' je veći od 5 MB.');const path=folder+'/'+Date.now()+'-'+Math.random().toString(36).slice(2,8)+'-'+cleanName(file.name);const {error}=await db.storage.from('deal-ns-images').upload(path,file,{upsert:false});if(error)throw error;return path}
async function refresh(){const {data,error}=await db.from('references').select('id,title,slug').order('created_at',{ascending:false});if(error)throw error;const el=$('#admin-list');el.innerHTML=data.length?data.map(r=>`<div class="admin-item"><strong>${r.title.replace(/[&<>"']/g,'')}</strong><a href="reference.html?id=${r.id}" target="_blank">Otvori</a><button data-del="${r.id}">Obriši</button></div>`).join(''):'Još nema referenci.';el.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>removeRef(Number(b.dataset.del)))}
async function removeRef(id){if(!confirm('Obrisati ovu referencu i njene fotografije?'))return;const {data:photos}=await db.from('photos').select('storage_path').eq('reference_id',id);if(photos?.length){const {error:e}=await db.storage.from('deal-ns-images').remove(photos.map(x=>x.storage_path));if(e)throw e}const {error}=await db.from('references').delete().eq('id',id);if(error)throw error;await refresh()}
$('#ref-form').onsubmit=async e=>{e.preventDefault();const m=$('#publish-msg');m.textContent='Objavljujem…';try{const title=$('#ref-title').value.trim(),slug=Date.now()+'-'+cleanName(title),files=[...$('#ref-images').files];const {data:r,error}=await db.from('references').insert({slug,title,short_description:$('#ref-short').value.trim(),description:$('#ref-description').value.trim(),published:true}).select('id').single();if(error)throw error;const paths=[];try{for(let i=0;i<files.length;i++){const p=await upload(files[i],'references/'+r.id);paths.push(p);const {error:pe}=await db.from('photos').insert({reference_id:r.id,storage_path:p,alt_text:title,sort_order:i,gallery_only:false});if(pe)throw pe}if(paths[0]){const {error:ce}=await db.from('references').update({cover_path:paths[0]}).eq('id',r.id);if(ce)throw ce}}catch(err){if(paths.length)await db.storage.from('deal-ns-images').remove(paths);await db.from('references').delete().eq('id',r.id);throw err}e.target.reset();m.textContent='Referenca je objavljena.';await refresh()}catch(err){m.textContent='Greška: '+err.message}};
$('#gallery-upload').onclick=async()=>{const m=$('#gallery-msg'),files=[...$('#gallery-images').files];if(!files.length){m.textContent='Izaberite fotografije.';return}m.textContent='Dodajem…';try{for(let i=0;i<files.length;i++){const p=await upload(files[i],'gallery');const {error}=await db.from('photos').insert({storage_path:p,alt_text:'DEAL NS radovi',sort_order:i,gallery_only:true});if(error){await db.storage.from('deal-ns-images').remove([p]);throw error}}$('#gallery-images').value='';m.textContent='Fotografije su dodate u galeriju.'}catch(err){m.textContent='Greška: '+err.message}};
showSession().catch(e=>{$('#login-msg').textContent='Greška: '+e.message});